### ISSUE TITLE
Neo4j Queries in /lib

### ISSUE THREAD

**Issue by bmarsh9** [chrismaddalena/Fox#2]
I have noticed a lot of the queries aren't returning matches. I had to change the OperatingSystem query and the PwdLastSet to return results. For example, the attribute 'OperatingSystem' was 'operatingsystem' (lowercase) in my bloodhound dataset. Setting everything to lowercase seemed to work. I was wondering if this is common or is my dataset somehow out of the ordinary that I have to lowercase the queries to Neo4j?

```
#        query = 
#        MATCH (c:Computer {domain:'%s'})
#        WHERE NOT (c.OperatingSystem = "" or c.OperatingSystem is Null)
#        RETURN DISTINCT(c.OperatingSystem) as OperatingSystems,COUNT(c.OperatingSystem) as Total
#        ORDER BY Total DESC
#         % domain
```

Changed to

```
        query = """
        MATCH (c:Computer {domain:'%s'})
        WHERE NOT (c.operatingsystem = "" or c.operatingsystem is Null)
        RETURN DISTINCT(c.operatingsystem) as operatingsystems,COUNT(c.operatingsystem) as Total
        ORDER BY Total DESC
        """ % domain
```
 
Maybe if there is a way to query all the attributes in the dataset and set global values so any functions can use the values for their queries?
Thanks!

**Comment by chrismaddalena** [comment]
Yeah, I have recently noticed this, too. Rohan and Andy have moved to using all lowercase for labels and Cypher is case sensitive, so now a bunch of Fox's queries are broken. There might be a way to check the labels beforehand to handle different casings, but if you are using a recent version of BloodHound updated queries with lowercase should work.

I'm going to update the queries soon. Thanks for the heads up!
